#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Human_Resources
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Employees")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Human_Resources.Properties.Settings.Default.EmployeesConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Employee> Employees
		{
			get
			{
				return this.GetTable<Employee>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employee")]
	[global::System.Data.Linq.Mapping.InheritanceMappingAttribute(Code="1", Type=typeof(Employee))]
	[global::System.Data.Linq.Mapping.InheritanceMappingAttribute(Code="2", Type=typeof(Employee2), IsDefault=true)]
	public partial class Employee
	{
		
		private int _Id;
		
		private string _First_Name;
		
		private string _Last_Name;
		
		private string _Sex;
		
		private string _Date_of_Birth;
		
		private string _Position;
		
		private string _Project;
		
		private string _Salary_Level;
		
		private int _Tel_;
		
		private string _Country;
		
		private string _Education_Level;
		
		private string _Training_;
		
		private string _Date_of_Employement;
		
		public Employee()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsDiscriminator=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[First Name]", Storage="_First_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string First_Name
		{
			get
			{
				return this._First_Name;
			}
			set
			{
				if ((this._First_Name != value))
				{
					this._First_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Last Name]", Storage="_Last_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Last_Name
		{
			get
			{
				return this._Last_Name;
			}
			set
			{
				if ((this._Last_Name != value))
				{
					this._Last_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this._Sex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Date of Birth]", Storage="_Date_of_Birth", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Date_of_Birth
		{
			get
			{
				return this._Date_of_Birth;
			}
			set
			{
				if ((this._Date_of_Birth != value))
				{
					this._Date_of_Birth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Position
		{
			get
			{
				return this._Position;
			}
			set
			{
				if ((this._Position != value))
				{
					this._Position = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Project", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Project
		{
			get
			{
				return this._Project;
			}
			set
			{
				if ((this._Project != value))
				{
					this._Project = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Salary Level]", Storage="_Salary_Level", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Salary_Level
		{
			get
			{
				return this._Salary_Level;
			}
			set
			{
				if ((this._Salary_Level != value))
				{
					this._Salary_Level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tel ]", Storage="_Tel_", DbType="Int NOT NULL")]
		public int Tel_
		{
			get
			{
				return this._Tel_;
			}
			set
			{
				if ((this._Tel_ != value))
				{
					this._Tel_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this._Country = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Education Level]", Storage="_Education_Level", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Education_Level
		{
			get
			{
				return this._Education_Level;
			}
			set
			{
				if ((this._Education_Level != value))
				{
					this._Education_Level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Training ]", Storage="_Training_", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Training_
		{
			get
			{
				return this._Training_;
			}
			set
			{
				if ((this._Training_ != value))
				{
					this._Training_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Date of Employement]", Storage="_Date_of_Employement", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Date_of_Employement
		{
			get
			{
				return this._Date_of_Employement;
			}
			set
			{
				if ((this._Date_of_Employement != value))
				{
					this._Date_of_Employement = value;
				}
			}
		}
	}
	
	public partial class Employee2 : Employee
	{
		
		private int _Id;
		
		private string _First_Name;
		
		private string _Last_Name;
		
		private string _Project;
		
		private string _Salary_Level;
		
		private int _Tel_;
		
		private string _Education_Level;
		
		private string _Training_;
		
		private string _Date_of_Employement;
		
		public Employee2()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[First Name]", Storage="_First_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string First_Name
		{
			get
			{
				return this._First_Name;
			}
			set
			{
				if ((this._First_Name != value))
				{
					this._First_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Last Name]", Storage="_Last_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Last_Name
		{
			get
			{
				return this._Last_Name;
			}
			set
			{
				if ((this._Last_Name != value))
				{
					this._Last_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Project", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Project
		{
			get
			{
				return this._Project;
			}
			set
			{
				if ((this._Project != value))
				{
					this._Project = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Salary Level]", Storage="_Salary_Level", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Salary_Level
		{
			get
			{
				return this._Salary_Level;
			}
			set
			{
				if ((this._Salary_Level != value))
				{
					this._Salary_Level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tel ]", Storage="_Tel_", DbType="Int NOT NULL")]
		public int Tel_
		{
			get
			{
				return this._Tel_;
			}
			set
			{
				if ((this._Tel_ != value))
				{
					this._Tel_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Education Level]", Storage="_Education_Level", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Education_Level
		{
			get
			{
				return this._Education_Level;
			}
			set
			{
				if ((this._Education_Level != value))
				{
					this._Education_Level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Training ]", Storage="_Training_", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Training_
		{
			get
			{
				return this._Training_;
			}
			set
			{
				if ((this._Training_ != value))
				{
					this._Training_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Date of Employement]", Storage="_Date_of_Employement", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Date_of_Employement
		{
			get
			{
				return this._Date_of_Employement;
			}
			set
			{
				if ((this._Date_of_Employement != value))
				{
					this._Date_of_Employement = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
